spring.application.name=ChatApplication
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=11111
spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin